default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check
        language: python
        additional_dependencies:
          - ruff==0.15.12
        types_or:
          - python
          - pyi

      - id: ruff-format
        name: ruff format
        entry: ruff format --check
        language: python
        additional_dependencies:
          - ruff==0.15.12
        types_or:
          - python
          - pyi

      - id: conventional-commit-message
        name: conventional commit message
        entry: python scripts/check_commit_msg.py
        language: python
        stages:
          - commit-msg
        pass_filenames: true
