export const SAMPLE_TRACE = [
    {
        label: 'Reset hard outbreak',
        reward: 0,
        done: false,
        action: null,
        observation: {
            regions: [
                { region: 'R1', reported_cases_d_ago: 52, hospital_load: 0.41, compliance_proxy: 0.75 },
                { region: 'R2', reported_cases_d_ago: 49, hospital_load: 0.39, compliance_proxy: 0.74 },
                { region: 'R3', reported_cases_d_ago: 56, hospital_load: 0.44, compliance_proxy: 0.72 },
                { region: 'R4', reported_cases_d_ago: 45, hospital_load: 0.36, compliance_proxy: 0.77 },
                { region: 'R5', reported_cases_d_ago: 47, hospital_load: 0.34, compliance_proxy: 0.78 },
            ],
            resources: { test_kits: 200, hospital_beds_free: 150, mobile_units: 5, vaccine_doses: 400 },
            active_restrictions: [],
            legal_constraints: [{ rule_id: 'L1', blocked_action: 'restrict_movement.strict', unlock_via: 'escalate' }],
            tick: 0,
            ticks_remaining: 12,
            cognition_budget_remaining: 6000,
            recent_action_log: [],
        },
    },
    {
        label: 'Escalation unlocks strict controls',
        reward: 0.11,
        done: false,
        action: { kind: 'escalate', to_authority: 'national' },
        observation: {
            regions: [
                { region: 'R1', reported_cases_d_ago: 55, hospital_load: 0.47, compliance_proxy: 0.74 },
                { region: 'R2', reported_cases_d_ago: 52, hospital_load: 0.43, compliance_proxy: 0.73 },
                { region: 'R3', reported_cases_d_ago: 62, hospital_load: 0.52, compliance_proxy: 0.70 },
                { region: 'R4', reported_cases_d_ago: 49, hospital_load: 0.40, compliance_proxy: 0.75 },
                { region: 'R5', reported_cases_d_ago: 48, hospital_load: 0.37, compliance_proxy: 0.77 },
            ],
            resources: { test_kits: 200, hospital_beds_free: 150, mobile_units: 5, vaccine_doses: 400 },
            active_restrictions: [],
            legal_constraints: [],
            tick: 1,
            ticks_remaining: 11,
            cognition_budget_remaining: 6000,
            recent_action_log: [
                { tick: 0, action: { kind: 'escalate', to_authority: 'national' }, accepted: true },
            ],
        },
    },
    {
        label: 'Strict restriction contains R3 pressure',
        reward: 0.19,
        done: false,
        action: { kind: 'restrict_movement', region: 'R3', severity: 'strict' },
        observation: {
            regions: [
                { region: 'R1', reported_cases_d_ago: 58, hospital_load: 0.48, compliance_proxy: 0.73 },
                { region: 'R2', reported_cases_d_ago: 55, hospital_load: 0.44, compliance_proxy: 0.72 },
                { region: 'R3', reported_cases_d_ago: 75, hospital_load: 0.61, compliance_proxy: 0.69 },
                { region: 'R4', reported_cases_d_ago: 51, hospital_load: 0.42, compliance_proxy: 0.75 },
                { region: 'R5', reported_cases_d_ago: 50, hospital_load: 0.39, compliance_proxy: 0.76 },
            ],
            resources: { test_kits: 200, hospital_beds_free: 150, mobile_units: 5, vaccine_doses: 400 },
            active_restrictions: [{ region: 'R3', severity: 'strict', ticks_remaining: 2 }],
            legal_constraints: [],
            tick: 2,
            ticks_remaining: 10,
            cognition_budget_remaining: 6000,
            recent_action_log: [
                { tick: 0, action: { kind: 'escalate', to_authority: 'national' }, accepted: true },
                { tick: 1, action: { kind: 'restrict_movement', region: 'R3', severity: 'strict' }, accepted: true },
            ],
        },
    },
    {
        label: 'Mobile units cover hospital load',
        reward: 0.24,
        done: false,
        action: { kind: 'deploy_resource', region: 'R3', resource_type: 'mobile_units', quantity: 3 },
        observation: {
            regions: [
                { region: 'R1', reported_cases_d_ago: 59, hospital_load: 0.48, compliance_proxy: 0.74 },
                { region: 'R2', reported_cases_d_ago: 57, hospital_load: 0.45, compliance_proxy: 0.72 },
                { region: 'R3', reported_cases_d_ago: 82, hospital_load: 0.56, compliance_proxy: 0.71 },
                { region: 'R4', reported_cases_d_ago: 54, hospital_load: 0.44, compliance_proxy: 0.75 },
                { region: 'R5', reported_cases_d_ago: 52, hospital_load: 0.40, compliance_proxy: 0.76 },
            ],
            resources: { test_kits: 200, hospital_beds_free: 150, mobile_units: 2, vaccine_doses: 400 },
            active_restrictions: [{ region: 'R3', severity: 'strict', ticks_remaining: 1 }],
            legal_constraints: [],
            tick: 3,
            ticks_remaining: 9,
            cognition_budget_remaining: 6000,
            recent_action_log: [
                { tick: 0, action: { kind: 'escalate', to_authority: 'national' }, accepted: true },
                { tick: 1, action: { kind: 'restrict_movement', region: 'R3', severity: 'strict' }, accepted: true },
                { tick: 2, action: { kind: 'deploy_resource', region: 'R3', resource_type: 'mobile_units', quantity: 3 }, accepted: true },
            ],
        },
    },
];
